/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_meta_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/disclaimer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disclaimer */
        get: operations["disclaimer_api_v1_meta_disclaimer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards */
        get: operations["list_cards_api_v1_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Card Facets */
        get: operations["card_facets_api_v1_cards_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Card Detail */
        get: operations["card_detail_api_v1_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Cards */
        post: operations["compare_cards_api_v1_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend */
        post: operations["recommend_api_v1_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Topics
         * @description Temas para aprender (glosario oficial de CONDUSEF).
         */
        get: operations["topics_api_v1_chat_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan
         * @description Paso 1 (D8): devuelve el plan explicito de tool calls antes de ejecutar.
         */
        post: operations["plan_api_v1_chat_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/runs/{run_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute
         * @description Paso 2: ejecuta el plan por niveles y genera la respuesta.
         */
        post: operations["execute_api_v1_chat_runs__run_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_chat_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_chat_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bi
         * @description BI de perfiles: solo administradores.
         */
        get: operations["bi_api_v1_bi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_admin_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/chat-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat Runs */
        get: operations["chat_runs_api_v1_admin_chat_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users */
        get: operations["users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionCount */
        ActionCount: {
            /** Action */
            action: string;
            /** Count */
            count: number;
        };
        /** AdminOverview */
        AdminOverview: {
            /** Users */
            users: number;
            /** Cards */
            cards: number;
            /** Fees */
            fees: number;
            /** Benefits */
            benefits: number;
            /** Events */
            events: number;
            /** Chat Runs */
            chat_runs: number;
            /** Recommendations */
            recommendations: number;
            /** By Action */
            by_action: components["schemas"]["ActionCount"][];
            /** Llm Enabled */
            llm_enabled: boolean;
            /** Database */
            database: string;
            /** Data Generated At */
            data_generated_at: string | null;
        };
        /** AdminUsers */
        AdminUsers: {
            /** Items */
            items: components["schemas"]["UserOut"][];
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** User Email */
            user_email: string | null;
            /** Action */
            action: string;
            /** Detail */
            detail: string;
            /** Duration Ms */
            duration_ms: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
        };
        /** AuditEventPage */
        AuditEventPage: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["AuditEventOut"][];
        };
        /** BIResponse */
        BIResponse: {
            kpis: components["schemas"]["Kpis"];
            /** By Class */
            by_class: components["schemas"]["LabelCount"][];
            /** By Institution */
            by_institution: components["schemas"]["LabelCount"][];
            /** Benefit Types */
            benefit_types: components["schemas"]["LabelCount"][];
            /** Fee Types */
            fee_types: components["schemas"]["LabelCount"][];
            /** Annual Fee Buckets */
            annual_fee_buckets: components["schemas"]["LabelCount"][];
            /** Profiles */
            profiles: components["schemas"]["ProfileStats"][];
            /** Scatter */
            scatter: components["schemas"]["ScatterPoint"][];
            model: components["schemas"]["ModelInfo"];
            report?: components["schemas"]["ProfileReport"] | null;
        };
        /** BenefitOut */
        BenefitOut: {
            /** Benefit Type */
            benefit_type: string;
            /** Text */
            text: string;
        };
        /** CardDetail */
        CardDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Institution */
            institution: string;
            /** Card Class */
            card_class: string;
            /** Cat */
            cat: number | null;
            /** Annual Fee */
            annual_fee: number | null;
            /** Interest Rate */
            interest_rate: number | null;
            /** Credit Line Min */
            credit_line_min: number | null;
            /** Monthly Income Min */
            monthly_income_min: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Image Orientation */
            image_orientation?: ("portrait" | "landscape") | null;
            /** Benefit Types */
            benefit_types: string[];
            fee_counts: components["schemas"]["FeeCounts"];
            profile: components["schemas"]["ProfileTag"];
            /** Institution Url */
            institution_url?: string | null;
            requirements: components["schemas"]["Requirements"];
            /** Fees */
            fees: components["schemas"]["FeeOut"][];
            /** Benefits */
            benefits: components["schemas"]["BenefitOut"][];
            /** Disclaimer */
            disclaimer: string;
        };
        /** CardFacets */
        CardFacets: {
            /** Institutions */
            institutions: string[];
            /** Classes */
            classes: string[];
            /** Benefit Types */
            benefit_types: string[];
            /** Profiles */
            profiles: components["schemas"]["ProfileTag"][];
            annual_fee: components["schemas"]["RangeOut"];
            cat: components["schemas"]["RangeOut"];
            interest_rate: components["schemas"]["RangeOut"];
        };
        /** CardListResponse */
        CardListResponse: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["CardSummary"][];
        };
        /** CardSummary */
        CardSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Institution */
            institution: string;
            /** Card Class */
            card_class: string;
            /** Cat */
            cat: number | null;
            /** Annual Fee */
            annual_fee: number | null;
            /** Interest Rate */
            interest_rate: number | null;
            /** Credit Line Min */
            credit_line_min: number | null;
            /** Monthly Income Min */
            monthly_income_min: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Image Orientation */
            image_orientation?: ("portrait" | "landscape") | null;
            /** Benefit Types */
            benefit_types: string[];
            fee_counts: components["schemas"]["FeeCounts"];
            profile: components["schemas"]["ProfileTag"];
        };
        /** ChatPlanResponse */
        ChatPlanResponse: {
            /** Run Id */
            run_id: string;
            /** Session Id */
            session_id: string;
            /** Plan */
            plan: components["schemas"]["PlanStep"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "rules" | "llm";
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id: string;
        };
        /** ChatRunResponse */
        ChatRunResponse: {
            /** Run Id */
            run_id: string;
            /** Session Id */
            session_id: string;
            /** Question */
            question: string;
            /** Plan */
            plan: components["schemas"]["PlanStep"][];
            /** Answer */
            answer: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "rules" | "llm";
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "ok" | "error";
            /** Cards */
            cards: components["schemas"]["CardSummary"][];
            /** Suggestions */
            suggestions: string[];
            /** Disclaimer */
            disclaimer: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
        };
        /** ChatRunSummary */
        ChatRunSummary: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** User Email */
            user_email: string;
            /** Session Id */
            session_id: string;
            /** Question */
            question: string;
            /** Mode */
            mode: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms: number;
            /** Steps */
            steps: number;
        };
        /** ChatTopicsResponse */
        ChatTopicsResponse: {
            /** Featured */
            featured: components["schemas"]["TopicOut"][];
            /** Total Terms */
            total_terms: number;
            /** Source */
            source: string;
        };
        /** ClusterReport */
        ClusterReport: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Blocks */
            blocks: components["schemas"]["ReportBlock"][];
        };
        /** CompareMetric */
        CompareMetric: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "MXN" | "%" | "count";
            /**
             * Better
             * @enum {string}
             */
            better: "lower" | "higher";
            /** Values */
            values: {
                [key: string]: number | null;
            };
            /** Best Id */
            best_id: string | null;
        };
        /** CompareRequest */
        CompareRequest: {
            /** Card Ids */
            card_ids: string[];
        };
        /** CompareResponse */
        CompareResponse: {
            /** Cards */
            cards: components["schemas"]["CardDetail"][];
            /** Metrics */
            metrics: components["schemas"]["CompareMetric"][];
            /** Disclaimer */
            disclaimer: string;
        };
        /** DisclaimerResponse */
        DisclaimerResponse: {
            /** Disclaimer */
            disclaimer: string;
        };
        /** FeeCounts */
        FeeCounts: {
            /**
             * Obligatoria
             * @default 0
             */
            obligatoria: number;
            /**
             * Por Evento
             * @default 0
             */
            por_evento: number;
            /**
             * Penalizacion
             * @default 0
             */
            penalizacion: number;
        };
        /** FeeOut */
        FeeOut: {
            /** Concept */
            concept: string;
            /** Amount */
            amount: number | null;
            /**
             * Denomination
             * @enum {string}
             */
            denomination: "MXN" | "USD" | "PCT";
            /**
             * Fee Type
             * @enum {string}
             */
            fee_type: "obligatoria" | "por_evento" | "penalizacion" | "otro";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Llm Enabled */
            llm_enabled: boolean;
            /** Cards Loaded */
            cards_loaded: number;
        };
        /** Kpis */
        Kpis: {
            /** Cards */
            cards: number;
            /** Institutions */
            institutions: number;
            /** No Annual Fee */
            no_annual_fee: number;
            /** Avg Cat */
            avg_cat: number;
            /** Avg Interest Rate */
            avg_interest_rate: number;
            /** Avg Annual Fee */
            avg_annual_fee: number;
            /** Benefits */
            benefits: number;
            /** Fees */
            fees: number;
        };
        /** LabelCount */
        LabelCount: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Version */
            version: string;
            /** Is Stub */
            is_stub: boolean;
            /** Features */
            features: string[];
            /** Description */
            description: string;
        };
        /** PlanStep */
        PlanStep: {
            /** Id */
            id: string;
            /**
             * Agent
             * @enum {string}
             */
            agent: "FundamentalsAgent" | "ComisionesAgent" | "EducativeAgent" | "PerfilAgent";
            /** Tool */
            tool: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Depends On */
            depends_on?: string[];
            /** Rationale */
            rationale: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "running" | "ok" | "error" | "skipped";
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Analytic Name
             * @default
             */
            analytic_name: string;
            /** Tagline */
            tagline: string;
            /** Description */
            description: string;
            /** Color */
            color: string;
            /** Icon */
            icon: string;
            /** Traits */
            traits: string[];
            /**
             * Card Count
             * @default 0
             */
            card_count: number;
        };
        /** ProfileReport */
        ProfileReport: {
            /** Source */
            source: string;
            /** Method */
            method: string[];
            /** Intro */
            intro: components["schemas"]["ReportBlock"][];
            /** Closing */
            closing: components["schemas"]["ReportBlock"][];
            /** Clusters */
            clusters: components["schemas"]["ClusterReport"][];
        };
        /** ProfileScore */
        ProfileScore: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Color */
            color: string;
            /** Score */
            score: number;
        };
        /** ProfileStats */
        ProfileStats: {
            profile: components["schemas"]["ProfileOut"];
            /** Avg Annual Fee */
            avg_annual_fee: number;
            /** Avg Interest Rate */
            avg_interest_rate: number;
            /** Avg Cat */
            avg_cat: number;
            /** Avg Credit Line */
            avg_credit_line: number;
            /** Top Benefits */
            top_benefits: components["schemas"]["LabelCount"][];
        };
        /**
         * ProfileTag
         * @description Perfil (cluster) al que pertenece una tarjeta.
         */
        ProfileTag: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Color */
            color: string;
            /**
             * Icon
             * @default
             */
            icon: string;
            /**
             * Tagline
             * @default
             */
            tagline: string;
        };
        /** RangeOut */
        RangeOut: {
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /** RecommendResponse */
        RecommendResponse: {
            profile: components["schemas"]["ProfileOut"];
            /** Profile Reason */
            profile_reason: string;
            /** Profile Scores */
            profile_scores: components["schemas"]["ProfileScore"][];
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /** Excluded Count */
            excluded_count: number;
            /** Assumptions */
            assumptions: string[];
            model: components["schemas"]["ModelInfo"];
            /** Disclaimer */
            disclaimer: string;
        };
        /** Recommendation */
        Recommendation: {
            card: components["schemas"]["CardSummary"];
            /** Score */
            score: number;
            /**
             * Eligibility
             * @enum {string}
             */
            eligibility: "cumple" | "por_confirmar" | "no_cumple";
            /** Reasons */
            reasons: string[];
            /** Warnings */
            warnings: string[];
        };
        /** ReportBlock */
        ReportBlock: {
            /** Kind */
            kind: string;
            /** Text */
            text: string;
        };
        /** Requirements */
        Requirements: {
            /** Age Min */
            age_min?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Score Min */
            score_min?: number | null;
            /** Work Seniority Min */
            work_seniority_min?: number | null;
            /** Residence Seniority Min */
            residence_seniority_min?: number | null;
            /** Monthly Income Min */
            monthly_income_min?: number | null;
        };
        /** ScatterPoint */
        ScatterPoint: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Institution */
            institution: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Profile Id */
            profile_id: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserOut"];
        };
        /** TopicOut */
        TopicOut: {
            /** Term */
            term: string;
            /** Category */
            category: string;
            /** Question */
            question: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "user";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at?: string | null;
        };
        /**
         * UserProfileIn
         * @description Datos NO sensibles: rangos y preferencias. Nunca RFC, CURP ni cuentas (D11).
         */
        UserProfileIn: {
            /**
             * Age
             * @description Edad en anios
             */
            age: number;
            /**
             * Income Range
             * @enum {string}
             */
            income_range: "lt_7k" | "7k_15k" | "15k_30k" | "30k_60k" | "gt_60k";
            /**
             * Credit Score
             * @default unknown
             * @enum {string}
             */
            credit_score: "unknown" | "none" | "low" | "medium" | "high";
            /** Work Seniority Months */
            work_seniority_months?: number | null;
            /**
             * Main Use
             * @default diario
             * @enum {string}
             */
            main_use: "diario" | "viajes" | "compras_meses" | "historial" | "transferir_saldo" | "emergencias";
            /**
             * Avoid Annual Fee
             * @default false
             */
            avoid_annual_fee: boolean;
            /**
             * Pays In Full
             * @description Obsoleto: usar payment_habit
             * @default false
             */
            pays_in_full: boolean;
            /**
             * Payment Habit
             * @description full=totalero, sometimes=a veces financia, revolving=suele financiar
             */
            payment_habit?: ("full" | "sometimes" | "revolving") | null;
            /**
             * Residence Months
             * @description Antiguedad en el domicilio
             */
            residence_months?: number | null;
            /**
             * Avoid Fees
             * @description Quiere evitar comisiones y penalizaciones altas
             * @default false
             */
            avoid_fees: boolean;
            /** Benefits */
            benefits?: ("Meses sin intereses" | "Puntos" | "Descuentos" | "Preventas" | "Transferencia de Saldo" | "Seguros")[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_meta_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    disclaimer_api_v1_meta_disclaimer_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisclaimerResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_cards_api_v1_cards_get: {
        parameters: {
            query?: {
                q?: string | null;
                institution?: string | null;
                card_class?: string | null;
                benefit_type?: string | null;
                profile_id?: number | null;
                max_annual_fee?: number | null;
                no_annual_fee?: boolean;
                sort?: "name" | "annual_fee" | "cat" | "interest_rate" | "credit_line_min" | "benefits";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    card_facets_api_v1_cards_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardFacets"];
                };
            };
        };
    };
    card_detail_api_v1_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_cards_api_v1_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_api_v1_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topics_api_v1_chat_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatTopicsResponse"];
                };
            };
        };
    };
    plan_api_v1_chat_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_api_v1_chat_runs__run_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_chat_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_chat_runs_get: {
        parameters: {
            query?: {
                session_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRunResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bi_api_v1_bi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BIResponse"];
                };
            };
        };
    };
    overview_api_v1_admin_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOverview"];
                };
            };
        };
    };
    events_api_v1_admin_events_get: {
        parameters: {
            query?: {
                action?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_runs_api_v1_admin_chat_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsers"];
                };
            };
        };
    };
}
